<?php if (session_status() === PHP_SESSION_NONE) session_start(); ?>
<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Shop | ClassyCubic</title><link rel="stylesheet" href="css/style.css"></head><body>
<?php include __DIR__ . '/includes/navbar.php'; ?>
<section class="section"><h2>🛍️ Available Products</h2><form class="search-bar" method="GET"><input id="productSearch" type="search" name="search" placeholder="Search products..." value="<?php echo htmlspecialchars($_GET['search'] ?? ''); ?>"><select name="category"><option value="">All Categories</option><option value="fashion">Fashion</option><option value="electronics">Electronics</option><option value="home">Home Appliances</option><option value="beauty">Beauty</option></select><button class="btn-primary" type="submit">Search</button></form><div class="products">
<?php include __DIR__.'/includes/db.php'; $search=trim($_GET['search']??''); $cat=$_GET['category']??''; $sql="SELECT * FROM products WHERE 1"; $types=''; $params=[]; if($search!==''){ $sql.=" AND name LIKE ?"; $types.='s'; $params[]="%$search%"; } if(in_array($cat,['fashion','electronics','home','beauty'],true)){ $sql.=" AND category=?"; $types.='s'; $params[]=$cat; } $sql.=" ORDER BY id DESC"; $st=mysqli_prepare($conn,$sql); if($params){mysqli_stmt_bind_param($st,$types,...$params);} mysqli_stmt_execute($st); $res=mysqli_stmt_get_result($st); while($p=mysqli_fetch_assoc($res)): ?>
<div class="product-card"><img src="<?php echo htmlspecialchars($p['image']); ?>" alt="Product"><h3><?php echo htmlspecialchars($p['name']); ?></h3><p class="price">৳<?php echo number_format($p['price'],2); ?></p><p><?php echo htmlspecialchars($p['description'] ?? ''); ?></p><p class="stock <?php echo $p['stock']<=0?'out-stock':'in-stock'; ?>">Stock: <?php echo (int)$p['stock']; ?></p><?php if((int)$p['stock']>0): ?><form method="POST" action="api/add_to_cart.php"><input type="hidden" name="product_id" value="<?php echo (int)$p['id']; ?>"><input class="qty-input" type="number" name="quantity" min="1" max="<?php echo (int)$p['stock']; ?>" value="1"><button class="add" type="submit">Add to Cart</button></form><?php else: ?><p class="out-stock">Out of Stock</p><?php endif; ?></div>
<?php endwhile; ?></div></section><script src="js/search.js"></script>
<footer><p>© 2026 ClassyCubic | All Rights Reserved</p></footer>
</body></html>